project:
  type: website
  output-dir: _site

website:
  title: "Forestly"
  description: "Forest Plot System for Clinical Trials"
  site-url: "https://elong0527.github.io/demo_sparkline"
  repo-url: "https://github.com/elong0527/demo_sparkline"
  repo-actions: [edit, issue]
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Examples"
        menu:
          - text: "Survival"
            href: example_survival.qmd
          - text: "Adverse Events"
            href: example_ae.qmd
    right:
      - icon: github
        href: https://github.com/elong0527/demo_sparkline
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
      - section: "Examples"
        contents:
          - example_survival.qmd
          - example_ae.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: true
    code-tools: true
    grid:
      body-width: 5000px
      sidebar-width: 250px
      margin-width: 250px
      gutter-width: 1.5rem

execute:
  freeze: auto
  cache: true
  
jupyter: python3

metadata-files:
  - _metadata.yml